#!/usr/bin/env bash
set -euo pipefail
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$ROOT"

fail() { echo "NATIVE_CONTRACT_FAIL: $*" >&2; exit 1; }

# Product/client implementation must remain compiled native code.
for path in app settings_center fcitx5/backend; do
  if [[ -d "$path" ]] && find "$path" -type f -print -quit | grep -q .; then
    fail "legacy client files remain under: $path"
  fi
done
for path in ibus/engine.py ibus/factory.py ibus/main.py ibus/rime_runtime.py \
            installers/check-python-runtime.py installers/setup-audio.py \
            installers/validate-installed-integration.py; do
  [[ ! -e "$path" ]] || fail "legacy Python product file remains: $path"
done

# Installed/build package paths cannot invoke Python or private venvs.
if rg -n '(^|[;&|[:space:]])python(3)?([[:space:]]|$)|PYTHONPATH|[^[:alnum:]_]\.py([[:space:]"'"'"')]|$)' \
    packaging/bin packaging/systemd packaging/tools/stage-system-package.sh \
    packaging/tools/build-{deb,rpm,arch}.sh installers/install-native-user.sh \
    fcitx5/scripts ibus/scripts; then
  fail "Python reference remains in an installed or package build path"
fi

# gedit/GTK replacement regression: validate first, then issue delete and commit
# in the same transaction. Never poll stale surrounding-text as an ACK.
replace_body=$(awk '
  /void VoCoTypeModule::replaceSurroundingText\(/ {capture=1}
  capture {print}
  capture && /void VoCoTypeModule::applyVoiceEditResult\(/ {exit}
' fcitx5/module/vocotype_module.cpp)
[[ "$replace_body" == *'voiceEditSnapshotStillMatches'* ]] || fail "replacement lacks preflight snapshot check"
[[ "$replace_body" == *'deleteSurroundingText'* ]] || fail "replacement lacks surrounding deletion"
[[ "$replace_body" == *'commitText(ic, new_text)'* ]] || fail "replacement lacks immediate commit"
delete_line=$(grep -n 'deleteSurroundingText' <<<"$replace_body" | head -1 | cut -d: -f1)
commit_line=$(grep -n 'commitText(ic, new_text)' <<<"$replace_body" | head -1 | cut -d: -f1)
(( delete_line < commit_line )) || fail "replacement commits before deleting"
[[ "$replace_body" != *'scheduleEditReplacementCheck'* ]] || fail "stale-cache polling returned"
[[ "$replace_body" != *'当前输入框不支持替换文本'* ]] || fail "stale-cache unsupported error returned"
! rg -q 'finalizeEditReplacement|edit_replace_retries_left_|edit_replace_timer_' fcitx5/module || fail "obsolete delayed replacement state remains"


rg -Fq '🎤 语音编辑中...' fcitx5/module/vocotype_module.cpp || \
  fail "clean voice-edit status title missing"
if rg -q 'del=|sur=1|active=1|edit_replace_state_' fcitx5/module; then
  fail "voice-edit debug capability probe remains"
fi
rg -Uq 'snapshot\.selected_text,\n[[:space:]]+"supported",\n[[:space:]]+true\);' \
  fcitx5/module/vocotype_module.cpp || \
  fail "valid surrounding context is not advertised as replace-capable"

# Exact polish status requested by product owner.
rg -Fq '正在润色... （等待模型输出 ' fcitx5/module/vocotype_module.cpp || fail "polish elapsed/timeout line missing"
rg -Fq '粗识别文本：' fcitx5/module/vocotype_module.cpp || fail "rough recognition line missing"
rg -Fq 'active_polish_started_us_' fcitx5/module/vocotype_module.cpp || fail "polish timer missing"

# The native settings window must cover every former product page/capability.
settings=native/desktop/src/settings_main.cpp
for token in \
  'list_output_devices' 'play_pcm16' 'draw_waveform' 'edit_audio' \
  'query_latest_release' 'create_support_bundle' 'submit_feedback' \
  'uninstall_integration' 'update_rime_schema' 'verify_native_payload' \
  '安装 / 修复 Fcitx 5' '安装 / 修复 IBus' '卸载 Fcitx 5 集成' \
  'Playground' 'Doctor 与支持' '反馈'; do
  rg -Fq "$token" "$settings" || fail "native settings capability missing: $token"
done


# The complete source tree contains no Python implementation or dependency
# manifest. Documentation is Markdown/static configuration; all executable
# product and service code is compiled C++ or lifecycle shell.
if find . \
    -path './.git' -prune -o \
    -path './build' -prune -o \
    -path './dist' -prune -o \
    -path './native/streaming_worker/build' -prune -o \
    -type f -name '*.py' -print -quit | grep -q .; then
  fail "Python source remains in the repository"
fi
if find . -path './.git' -prune -o -path './build' -prune -o \
    -type f \( -name 'pyproject.toml' -o -name 'uv.lock' -o \
    -name 'requirements*.txt' \) -print -quit | grep -q .; then
  fail "Python dependency manifest remains in the repository"
fi
for token in \
  'add_executable(vocotype-feedback' \
  'Boost.Beast' \
  'vocotype-feedback serve' \
  '/opt/vocotype-feedback/bin/vocotype-feedback'; do
  rg -Fq "$token" feedback_service deploy/feedback || \
    fail "native feedback capability missing: $token"
done


# Documentation publishing is also compiled/static and must not reintroduce a
# Python site generator.
for token in \
  'tools/build-static-site.sh build/pages' \
  'tools/docs_builder.cpp' \
  'Generated by the compiled VoCoType documentation builder'; do
  rg -Fq "$token" .github/workflows/pages.yml tools/docs_builder.cpp || \
    fail "native documentation build token missing: $token"
done
if rg -n 'setup-python|mkdocs|requirements-docs|pip install' \
    .github/workflows/pages.yml tools/build-static-site.sh; then
  fail "Python documentation build dependency remains"
fi

# Native package metadata has no Python build/runtime dependency.
for format in debian rpm arch; do
  case "$format" in
    debian) template=packaging/debian/control ;;
    rpm) template=packaging/rpm/vocotype.spec.in ;;
    arch) template=packaging/arch/PKGBUILD.in ;;
  esac
  for flavor in universal ibus fcitx5; do
    output=$(mktemp)
    packaging/tools/render-package-metadata.sh --format "$format" \
      --flavor "$flavor" --template "$template" --output "$output"
    if grep -Ei '(^|[ ,:])python([0-9.-]|$)|wheelhouse|virtualenv|PyGObject|numpy|sounddevice' "$output"; then
      rm -f "$output"
      fail "$format/$flavor metadata contains Python dependency"
    fi
    rm -f "$output"
  done
done

echo NATIVE_CONTRACTS_OK
